name: "P6 GHA: Builds a CDKTF App"
description: "P6 GHA: Builds a CDKTF App"
author: "Philip M. Gollucci"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install Node.js
      shell: bash
      run: |
        set +e
        curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node-v22.11.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.11.0-linux-x64.tar.xz -C /usr/local
        ls -alFh /usr/local
        sudo chmod -R 777 /usr/local/node-v22.11.0-linux-x64
        echo "/usr/local/node-v22.11.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Corepack
      shell: bash
      run: |
        set +e
        echo $PATH
        which corepack
        sudo /usr/local/node-v22.11.0-linux-x64/bin/corepack enable
        sudo /usr/local/node-v22.11.0-linux-x64/bin/corepack prepare pnpm@latest --activate
    - name: Restore NPM node_modules
      uses: actions/cache/restore@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: Check Node
      shell: bash
      run: |
        set +e
        which node
        which npm
        which pnpm
        which corepack
        node -v
        npm -v
        pnpm --version
        corepack --version
        echo $PATH
    - name: Install pnpm and dependencies
      shell: bash
      run: pnpm install
    - name: Cache NPM dependencies
      uses: actions/cache@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: CDKTF bootstrap
      shell: bash
      run: |
        /usr/local/node-v22.11.0-linux-x64/bin/npm install --global cdktf-cli@latest
        which cdktf
        cdktf --version
    - name: Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.5.7
    - name: Run build
      shell: bash
      run: pnpm run diff
